---
- name: Run set-up playbook
  delegate_to: localhost
  # Fixme: shold use the environment
  shell: ansible-playbook ~/.files/homelab/vms/set-up.yaml --inventory infra/inventories/staging

# Fixmeyou can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024),

- name: Stop exiting services
  shell: ~/.local/bin/just down
  ignore_errors: true

- name: Remove deployment directory
  file:
    path: "{{ deployment_path }}"
    state: absent
  become: true

- name: Create deployment directory
  file:
    path: "{{ deployment_path }}"
    state: directory
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
    mode: "0755"

- name: Create images directory
  file:
    path: "{{ deployment_path }}/images"
    state: directory
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
    mode: "0755"

- name: Create database data directory
  file:
    path: "{{ deployment_path }}/database-data"
    state: directory
    owner: "{{ deployment_user }}"
    group: "{{ deployment_user }}"
    mode: "0755"
