<script lang="ts">
	import SectionHead from '$lib/components/SectionHead.svelte';
	import { ChevronLeft } from '@lucide/svelte';

	const lastUpdated = 'June 28, 2026';
</script>

<svelte:head>
	<title>Terms of Service - Symbology</title>
	<meta name="description" content="The terms governing your use of Symbology." />
</svelte:head>

<!-- Back link -->
<div class="hidden md:block" style="margin-bottom: 3rem;">
	<a
		href="/"
		class="meta flex items-center gap-1.5 text-ink-3 no-underline transition-colors hover:text-ink"
	>
		<ChevronLeft class="h-3 w-3" />
		Home
	</a>
</div>

<!-- Masthead -->
<header style="max-width: 720px;">
	<div class="eyebrow" style="margin-bottom: 1rem;">
		<span style="color: var(--teal-2);">&#9679;</span>&nbsp;&nbsp;LEGAL
	</div>
	<h1 class="display" style="margin-bottom: 1rem;">Terms of Service</h1>
	<p class="lede" style="color: var(--ink-2); max-width: 52ch;">
		The agreement between you and Streetfortress Industries, LLC governing your use of Symbology.
	</p>
	<p class="meta" style="color: var(--ink-3); margin-top: 1rem;">Last updated: {lastUpdated}</p>
</header>

<!-- Content -->
<article style="margin-top: 5rem;">
	<div class="analysis-body">
		<section>
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="1. Acceptance of terms"
			/>
			<p>
				Symbology (the "Service") is operated by Streetfortress Industries, LLC ("we", "us", or
				"our"). By accessing or using the Service, you agree to be bound by these Terms of Service
				(the "Terms"). If you do not agree to these Terms, do not use the Service. Your use of the
				Service is also governed by our
				<a
					href="/privacy"
					style="color: var(--teal-2); text-decoration: underline; text-underline-offset: 3px;"
					>Privacy Policy</a
				>.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="2. What Symbology is" />
			<p>
				Symbology pulls public filings from the U.S. Securities and Exchange Commission (SEC) and
				uses large language models to summarize, compare, and synthesize them into structured,
				readable intelligence. The Service is an informational and research tool. It is not a
				broker-dealer, investment adviser, or financial institution, and it does not facilitate the
				purchase or sale of any security.
			</p>
		</section>

		<section id="not-investment-advice" style="margin-top: 3rem; scroll-margin-top: 5rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="3. Not investment advice"
			/>
			<p>
				<strong style="color: var(--ink);"
					>Symbology does not provide investment, financial, legal, tax, or accounting advice.</strong
				>
				All content on the Service is provided for general informational purposes only and must not be
				relied upon as the basis for any investment or other decision. Nothing on the Service is a recommendation,
				offer, or solicitation to buy or sell any security or to adopt any investment strategy.
			</p>
			<p>
				A substantial portion of the Service's content is <strong style="color: var(--ink);"
					>generated by automated systems and large language models</strong
				>
				and may be incomplete, out of date, or incorrect, including factual errors ("hallucinations").
				The original SEC filings are the authoritative source; where the synthesis and a filing disagree,
				the filing controls. You are solely responsible for independently verifying any information before
				relying on it, and you should consult a qualified professional before making any financial decision.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="4. Eligibility & accounts"
			/>
			<p>
				You must be at least 18 years old and capable of forming a binding contract to use the
				Service. When you create an account you agree to provide accurate information, to keep your
				credentials confidential, and to remain responsible for all activity that occurs under your
				account. Notify us promptly of any unauthorized use. We may suspend or terminate accounts
				that violate these Terms.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="5. Supporter contributions & payments"
			/>
			<p>
				You may choose to make a one-time supporter contribution to help fund the Service. Payments
				are processed by our third-party payment processor, Stripe; we do not receive or store your
				full card details. A contribution grants access to supporter features for the period
				described at checkout.
			</p>
			<p>
				<strong style="color: var(--ink);">All payments are final and non-refundable</strong>,
				except where a refund is required by law. Prices are stated in U.S. dollars and you are
				responsible for any applicable taxes. We may change supporter pricing or features at any
				time; changes will not affect contributions already made.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="6. Acceptable use" />
			<p>You agree not to:</p>
			<ul style="margin: 1rem 0; padding-left: 1.5rem; list-style: disc; color: var(--ink-2);">
				<li style="margin-bottom: 0.5rem;">
					use the Service in violation of any applicable law or regulation;
				</li>
				<li style="margin-bottom: 0.5rem;">
					scrape, crawl, bulk-download, or use automated means to access the Service except as
					expressly permitted;
				</li>
				<li style="margin-bottom: 0.5rem;">
					resell, sublicense, or redistribute the Service's generated content as a competing data
					product;
				</li>
				<li style="margin-bottom: 0.5rem;">
					attempt to disrupt, overload, reverse engineer, or circumvent any security or access
					controls of the Service;
				</li>
				<li style="margin-bottom: 0.5rem;">
					misrepresent your identity or use the Service to infringe the rights of others.
				</li>
			</ul>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="7. Intellectual property"
			/>
			<p>
				SEC filings are public records. The Service's original synthesis, summaries, comparisons,
				software, design, and branding are owned by Streetfortress Industries, LLC and protected by
				intellectual-property laws. Subject to these Terms, we grant you a limited, non-exclusive,
				non-transferable, revocable license to access and use the Service for your own personal or
				internal business research. All rights not expressly granted are reserved.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="8. Third-party services"
			/>
			<p>
				The Service relies on and links to third-party services, including Stripe (payments), Resend
				(email delivery), and others described in our Privacy Policy. We are not responsible for the
				content, policies, or practices of third parties, and your use of them may be subject to
				their own terms.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="9. Disclaimer of warranties"
			/>
			<p>
				The Service is provided <strong style="color: var(--ink);"
					>"as is" and "as available"</strong
				>, without warranties of any kind, whether express or implied, including implied warranties
				of merchantability, fitness for a particular purpose, accuracy, and non-infringement. We do
				not warrant that the Service will be uninterrupted, error-free, secure, or that any content
				is accurate, complete, or current.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="10. Limitation of liability"
			/>
			<p>
				To the fullest extent permitted by law, Streetfortress Industries, LLC and its members,
				officers, and contributors will not be liable for any indirect, incidental, special,
				consequential, or punitive damages, or any loss of profits, data, or goodwill, arising out
				of or relating to your use of (or inability to use) the Service — including any reliance on
				generated content. Our total aggregate liability for any claim relating to the Service will
				not exceed the greater of the amount you paid us in the twelve months preceding the claim or
				USD $100.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="11. Indemnification" />
			<p>
				You agree to indemnify and hold harmless Streetfortress Industries, LLC from any claims,
				losses, liabilities, and expenses (including reasonable legal fees) arising out of your use
				of the Service, your violation of these Terms, or your violation of any rights of a third
				party.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="12. Termination" />
			<p>
				You may stop using the Service at any time. We may suspend or terminate your access at any
				time, with or without notice, if we reasonably believe you have violated these Terms or to
				protect the Service or its users. Provisions that by their nature should survive termination
				(including intellectual property, disclaimers, limitation of liability, and indemnification)
				will survive.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead
				sticky
				stickyHeading
				eyebrow="Terms of Service"
				heading="13. Changes to these Terms"
			/>
			<p>
				We may update these Terms from time to time. When we do, we will revise the "Last updated"
				date above and, where appropriate, provide additional notice. Your continued use of the
				Service after changes take effect constitutes acceptance of the revised Terms.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="14. Governing law" />
			<p>
				These Terms are governed by the laws of the State of Washington, without regard to its
				conflict-of-laws rules. You agree that the state and federal courts located in Washington
				will have exclusive jurisdiction over any dispute arising out of or relating to these Terms
				or the Service.
			</p>
		</section>

		<section style="margin-top: 3rem;">
			<SectionHead sticky stickyHeading eyebrow="Terms of Service" heading="15. Contact" />
			<p>
				Questions about these Terms can be sent to
				<a
					href="mailto:support@streetfortress.com"
					style="color: var(--teal-2); text-decoration: underline; text-underline-offset: 3px;"
					>support@streetfortress.com</a
				>.
			</p>
		</section>
	</div>

	<div class="meta mt-6 flex justify-start border-t pt-6 text-ink-3 md:justify-end">
		<p>
			See also our
			<a href="/privacy" style="color: var(--teal-2); text-decoration: none;">Privacy Policy</a>.
		</p>
	</div>
</article>
