creation_rules:
    - path_regex: ^secrets/.*\.env$
      age:
        - age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x # devbox
        - age1kzhsyptaa93d3gxfw2ymcr2sv5cs94lk9p68m35r3jdjek3scqtqycv0jt # gitea action runner
