creation_rules:
  - path_regex: ^secrets/.*\.env$
    age:
      - age1rgr7hqdjsu4y3m98z3yw7cfwf9w8q4xdvmrv4jc97na32svm5y2qtpsw9x # devbox
      - age1j7nqengyuhy0pq7njesq40futtkme9erk5xgv3sf04rm8cjx4gmqesqp29 # gitea action runner
