services:
  symbology-ui:
    image: symbology-ui
    container_name: symbology_ui
    restart: unless-stopped
    environment:
      SYMBOLOGY_API_HOST: ${SYMBOLOGY_API_HOST:-10.0.0.3}
      SYMBOLOGY_API_PORT: ${SYMBOLOGY_API_PORT:-8000}
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
    ports:
      - 3003:80

