[project]
name = "symbology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edgartools>=3.13.3",
    "jupyter>=1.1.1",
    "ollama>=0.4.7",
]
