services:
  symbology-ui:
    image: symbology-ui
    container_name: symbology-ui
    restart: always
    environment:
      - PUBLIC_SYMBOLOGY_API_HOST=api.symbology.online
      - PUBLIC_LOG_LEVEL=INFO
      - PUBLIC_ENVIRONMENT=production
    # # these were previously passed in at build time and may no longer be necessary
    #   - SYMBOLOGY_API_PORT="443"
    ports:
      - 3000:3000
    networks:
      - caddy_network

  symbology-api:
    image: symbology-collector
    container_name: symbology-api
    restart: always
    environment:
      SYMBOLOGY_API_HOST: 0.0.0.0 # may not be necessary with our caddy config
      SYMBOLOGY_API_PORT: 3001
      DATABASE_HOST: ${DATABASE_HOST:-localhost}
    networks:
      - caddy_network

  # go-api:
  #   image: symbology-api:latest
  #   container_name: symbology-go-api
  #   env_file: .env
  #   restart: unless-stopped

networks:
  caddy_network:
    driver: bridge
