{
 "title": "Symbology Staging",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "linux_vm",
    "query": {
     "query": "query_result(up{job=\"linux_vms\", instance=~\"staging.*\"} == 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$linux_vm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "linux_vm" },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_http\", instance=\"$linux_vm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Symbology API Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"$linux_vm\"} != \"uvicorn\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"{{.host}} {{.level}} {{.caller}} {{.function}}\"[$__auto]))",
     "legendFormat": "api {{level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"container\", container_name=\"symbology-api\", host=\"$linux_vm\"} |= \"log_client_message\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json [$__auto]))",
     "legendFormat": "ui {{level}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$linux_vm\"}[$__rate_interval])) * 100)",
     "legendFormat": "Core {{cpu}}"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=\"$linux_vm\"}[$__rate_interval ])) * 100)",
     "legendFormat": "all_cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$linux_vm\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$linux_vm\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Symbology API Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-api\", host=\"$linux_vm\"} != \"uvicorn\" != \"log_client_message\"| json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"api {{.level}}\\t{{.caller}}\\t{{.function}}\\t{{.event}}\"",
     "legendFormat": "symbology-api"
    },
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-api\", host=\"staging-1g\"} |= \"log_client_message\" | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{ .log }}\" | json | line_format \"ui  {{.level}}\\t{{.component}}\\t{{.event}}\"",
     "legendFormat": "uvicorn"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$linux_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
     "legendFormat": "Tx"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$linux_vm\",device=\"ens3\"}[$__rate_interval]) * 8",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$linux_vm\",mountpoint=\"/\"} - node_filesystem_free_bytes",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$linux_vm\",mountpoint=\"/\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Symbology UI Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({job=\"container\", container_name=\"symbology-ui\", host=\"$linux_vm\"} | json | line_format \"{{.log}}\" | json log | line_format \"{{.timestamp}}\\t{{.level}}\\t{{.log}}\"[$__auto]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Symbology Database Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (count_over_time({job=\"container\", service_name=\"symbology-database\", host=\"$linux_vm\"}[$__auto]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Symbology UI",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-ui\", host=\"staging-1g\"} | json | line_format \"{{.log}}\" | json log | line_format \"{{.container_name}}\\t{{.detected_level}}\\t{{.log}}\"",
     "legendFormat": "symbology-api"
    }
   ]
  },
  {
   "title": "Symbology Database",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"container\", container_name=\"symbology-database\", host=\"$linux_vm\"} | json | line_format \"{{ .log }}\" | json | json log | line_format \"{{.stream}}\\t{{ .log }}\"",
     "legendFormat": "symbology-api"
    }
   ]
  }
 ]
}