services:
  postgres:
    image: postgres:17.4 # use the latest image.
    container_name: postgres
    restart: unless-stopped
    environment: # set required env variables to access postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpassword}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes: # optional to preserve database after container is deleted.
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: elestio/pgadmin:REL-9_0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpassword}
      PFADMIN_LISTEN_PORT: 8080
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - ./pgadmin-data/pgadmin-servers.json:/pgadmin4/servers.json
      - ./pgadmin-data/pgpass:/pgpass
    depends_on:
      - postgres
