/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/companies/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Search Companies Partial
		 * @description Search for companies by partial name or ticker.
		 *
		 *     Returns a list of companies that match the search query.
		 *     This is primarily used for autocomplete functionality.
		 */
		get: operations['search_companies_partial_companies_search_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/companies/id/{company_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Company By Id Route
		 * @description Get a company by its ID.
		 */
		get: operations['get_company_by_id_route_companies_id__company_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/companies/by-ticker/{ticker}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Company By Ticker Route
		 * @description Get a company by its ticker symbol.
		 */
		get: operations['get_company_by_ticker_route_companies_by_ticker__ticker__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/companies': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Companies Route
		 * @description Get companies with various filtering options.
		 *
		 *     Can be used for:
		 *     - Searching companies by name/ticker with 'search' parameter
		 *     - Getting paginated list with 'skip' and 'limit' parameters
		 *     - Finding specific company by 'ticker'
		 */
		get: operations['get_companies_route_companies_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/documents/{document_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Document By Id
		 * @description Get a document by its ID.
		 */
		get: operations['get_document_by_id_documents__document_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/documents/{document_id}/content': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Document Content
		 * @description Get a document's content by its ID.
		 */
		get: operations['get_document_content_documents__document_id__content_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/documents/by-filing/{filing_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Documents By Filing Id
		 * @description Get all documents for a specific filing.
		 */
		get: operations['get_documents_by_filing_id_documents_by_filing__filing_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/documents/by-ids': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Get Documents By Ids
		 * @description Get documents by their IDs.
		 */
		post: operations['get_documents_by_ids_documents_by_ids_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/documents/by-accession/{accession_number}/{content_hash}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Document By Accession And Hash
		 * @description Get a document by filing accession number and content hash.
		 *
		 *     This endpoint supports the new URL pattern: /d/[accession_number]/[content_hash]
		 *
		 *     Args:
		 *         accession_number: SEC filing accession number (e.g., "0001326380-21-000032")
		 *         content_hash: Full or partial SHA256 hash of document content (e.g., "c2b97228e5a1")
		 *
		 *     Returns:
		 *         DocumentResponse object with document details and filing information
		 */
		get: operations['get_document_by_accession_and_hash_documents_by_accession__accession_number___content_hash__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/filings/by-company/{company_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Company Filings
		 * @description Get all filings for a specific company.
		 *
		 *     Args:
		 *         company_id: UUID of the company
		 *
		 *     Returns:
		 *         List of filings for the company
		 */
		get: operations['get_company_filings_filings_by_company__company_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/filings/by-ticker/{ticker}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Filings By Ticker
		 * @description Get all filings for a company by ticker symbol.
		 *
		 *     Args:
		 *         ticker: Stock ticker symbol
		 *
		 *     Returns:
		 *         List of filings for the company with that ticker
		 */
		get: operations['get_filings_by_ticker_filings_by_ticker__ticker__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/filings/{accession_number}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Filing By Accession
		 * @description Get a specific filing by its accession number.
		 *
		 *     Args:
		 *         accession_number: SEC accession number (e.g., 0001326380-22-000021)
		 *
		 *     Returns:
		 *         Filing details
		 */
		get: operations['get_filing_by_accession_filings__accession_number__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/filings/{accession_number}/documents': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Filing Documents By Accession
		 * @description Get all documents for a filing by its accession number.
		 *
		 *     Args:
		 *         accession_number: SEC accession number
		 *
		 *     Returns:
		 *         List of documents in the filing
		 */
		get: operations['get_filing_documents_by_accession_filings__accession_number__documents_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/filings/{accession_number}/company': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Filing Company By Accession
		 * @description Get the company information for a filing by its accession number.
		 *
		 *     Args:
		 *         accession_number: SEC accession number
		 *
		 *     Returns:
		 *         Company details
		 */
		get: operations['get_filing_company_by_accession_filings__accession_number__company_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/prompts/{prompt_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Prompt By Id
		 * @description Get a specific prompt by ID.
		 */
		get: operations['get_prompt_by_id_prompts__prompt_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/by-ticker/{ticker}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Company Generated Content By Ticker
		 * @description Get the most recent generated content for each document type by ticker.
		 *
		 *     Returns only the most recent content for each document type to avoid duplicates
		 *     and ensure you get the latest AI-generated insights.
		 *
		 *     Args:
		 *         ticker: Company ticker symbol (e.g., 'AAPL', 'GOOGL')
		 *         limit: Maximum number of results to return (default: 10)
		 *
		 *     Returns:
		 *         List of GeneratedContentResponse objects - the most recent content for each document type
		 */
		get: operations['get_company_generated_content_by_ticker_generated_content_by_ticker__ticker__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/aggregate-summaries/by-ticker/{ticker}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Aggregate Summaries By Ticker Route
		 * @description Get the most recent aggregate summary content for a company by ticker.
		 *
		 *     Returns only aggregate summaries (content with descriptions containing "aggregate_summary")
		 *     to show high-level insights and summaries for each document type.
		 *
		 *     Args:
		 *         ticker: Company ticker symbol (e.g., 'AAPL', 'GOOGL')
		 *         limit: Maximum number of results to return (default: 10)
		 *
		 *     Returns:
		 *         List of GeneratedContentResponse objects - the most recent aggregate summaries
		 */
		get: operations['get_aggregate_summaries_by_ticker_route_generated_content_aggregate_summaries_by_ticker__ticker__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/by-ticker/{ticker}/{content_hash}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Generated Content By Ticker And Hash
		 * @description Get generated content by ticker and content hash for URL routing.
		 *
		 *     This endpoint supports the URL format: /g/{ticker}/{hash}
		 *
		 *     Args:
		 *         ticker: Company ticker symbol
		 *         content_hash: Full or partial SHA256 hash of the content
		 *
		 *     Returns:
		 *         GeneratedContentResponse object with the content details
		 */
		get: operations['get_generated_content_by_ticker_and_hash_generated_content_by_ticker__ticker___content_hash__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/{content_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Generated Content By Id
		 * @description Get generated content by its ID.
		 *
		 *     Args:
		 *         content_id: UUID of the generated content
		 *
		 *     Returns:
		 *         GeneratedContentResponse object with the content details
		 */
		get: operations['get_generated_content_by_id_generated_content__content_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/by-hash/{content_hash}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Generated Content By Hash Only
		 * @description Get generated content by its content hash only.
		 *
		 *     Args:
		 *         content_hash: Full or partial SHA256 hash of the content
		 *
		 *     Returns:
		 *         GeneratedContentResponse object with the content details
		 */
		get: operations['get_generated_content_by_hash_only_generated_content_by_hash__content_hash__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/generated-content/{content_id}/sources': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Generated Content Sources
		 * @description Get all sources (documents and other content) for a generated content.
		 *
		 *     Args:
		 *         content_id: UUID of the generated content
		 *
		 *     Returns:
		 *         Dictionary with source documents and source content lists
		 */
		get: operations['get_generated_content_sources_generated_content__content_id__sources_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Jobs Route
		 * @description List jobs with optional filters.
		 */
		get: operations['list_jobs_route_jobs_get'];
		put?: never;
		/**
		 * Enqueue Job
		 * @description Submit a new job to the queue.
		 */
		post: operations['enqueue_job_jobs_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{job_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Job By Id
		 * @description Get a job by its ID.
		 */
		get: operations['get_job_by_id_jobs__job_id__get'];
		put?: never;
		post?: never;
		/**
		 * Cancel Job Route
		 * @description Cancel a pending job.
		 */
		delete: operations['cancel_job_route_jobs__job_id__delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/model-configs/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List All Model Configs
		 * @description Get all model configurations.
		 *
		 *     Returns:
		 *         List of ModelConfigResponse objects
		 */
		get: operations['list_all_model_configs_model_configs__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/model-configs/{config_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Model Config By Id
		 * @description Get model configuration by its ID.
		 *
		 *     Args:
		 *         config_id: UUID of the model configuration
		 *
		 *     Returns:
		 *         ModelConfigResponse object with the configuration details
		 */
		get: operations['get_model_config_by_id_model_configs__config_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/model-configs/by-name/{model_name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Model Config By Model Name
		 * @description Get model configuration by model name.
		 *
		 *     Args:
		 *         model_name: Name of the model (e.g., 'qwen3:14b', 'gemma3:12b')
		 *
		 *     Returns:
		 *         ModelConfigResponse object with the configuration details
		 */
		get: operations['get_model_config_by_model_name_model_configs_by_name__model_name__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/pipeline/runs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Runs
		 * @description List pipeline runs with optional filters.
		 */
		get: operations['list_runs_pipeline_runs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/pipeline/runs/{run_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Run
		 * @description Get a single pipeline run by ID.
		 */
		get: operations['get_run_pipeline_runs__run_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/pipeline/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Pipeline Status Dashboard
		 * @description Dashboard showing latest pipeline run per company with failure counts.
		 */
		get: operations['pipeline_status_dashboard_pipeline_status_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/pipeline/trigger/{ticker}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Trigger Pipeline
		 * @description Manually trigger a pipeline run for a company.
		 */
		post: operations['trigger_pipeline_pipeline_trigger__ticker__post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Search
		 * @description Unified full-text search across companies, filings, and generated content.
		 *
		 *     Supports full-text search with relevance ranking, filtering by entity type,
		 *     SIC code, form type, document type, and date range.
		 */
		get: operations['search_search_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Root
		 * @description Root endpoint for API health check.
		 */
		get: operations['root_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * CompanyPipelineStatus
		 * @description Pipeline status for a single company.
		 */
		CompanyPipelineStatus: {
			/**
			 * Company Id
			 * Format: uuid
			 * @description Company identifier
			 */
			company_id: string;
			/**
			 * Ticker
			 * @description Company ticker symbol
			 */
			ticker?: string | null;
			/**
			 * Company Name
			 * @description Company name
			 */
			company_name?: string | null;
			/**
			 * Last Run Id
			 * @description Most recent run ID
			 */
			last_run_id?: string | null;
			/**
			 * Last Run Status
			 * @description Most recent run status
			 */
			last_run_status?: string | null;
			/**
			 * Last Run At
			 * @description When the last run started
			 */
			last_run_at?: string | null;
			/**
			 * Consecutive Failures
			 * @description Consecutive FAILED/PARTIAL runs
			 * @default 0
			 */
			consecutive_failures: number;
		};
		/**
		 * CompanyResponse
		 * @description Response schema for a company.
		 * @example {
		 *       "display_name": "Apple Inc.",
		 *       "exchanges": [
		 *         "NASDAQ"
		 *       ],
		 *       "fiscal_year_end": "2023-09-30",
		 *       "former_names": [
		 *         {
		 *           "date_changed": "2007-01-09",
		 *           "name": "Apple Computer, Inc."
		 *         }
		 *       ],
		 *       "id": "123e4567-e89b-12d3-a456-426614174000",
		 *       "name": "Apple Inc.",
		 *       "sic": "3571",
		 *       "sic_description": "Electronic Computers",
		 *       "summary": "Apple Inc. is a leading technology company that designs, develops and sells consumer electronics, computer software and online services...",
		 *       "ticker": "AAPL"
		 *     }
		 */
		CompanyResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the company
			 */
			id: string;
			/**
			 * Name
			 * @description Company name
			 */
			name: string;
			/**
			 * Display Name
			 * @description Display name for the company
			 */
			display_name?: string | null;
			/**
			 * Ticker
			 * @description Company tikcer symbol
			 */
			ticker: string;
			/**
			 * Exchanges
			 * @description List of exchanges where company is listed
			 */
			exchanges?: string[];
			/**
			 * Sic
			 * @description Standard Industrial Classification code
			 */
			sic?: string | null;
			/**
			 * Sic Description
			 * @description Description of the SIC code
			 */
			sic_description?: string | null;
			/**
			 * Fiscal Year End
			 * @description Date of fiscal year end
			 */
			fiscal_year_end?: string | null;
			/**
			 * Former Names
			 * @description List of former company names
			 */
			former_names?: {
				[key: string]: unknown;
			}[];
			/**
			 * Summary
			 * @description Generated company summary based on aggregated analysis
			 */
			summary?: string | null;
		};
		/**
		 * DocumentResponse
		 * @description Response schema for a document.
		 * @example {
		 *       "company_id": "123e4567-e89b-12d3-a456-426614174000",
		 *       "content": "<p>This is a sample document content...</p>",
		 *       "filing": {
		 *         "accession_number": "0000320193-23-000077",
		 *         "company_id": "123e4567-e89b-12d3-a456-426614174000",
		 *         "filing_date": "2023-11-03",
		 *         "form": "10-K",
		 *         "id": "123e4567-e89b-12d3-a456-426614174001",
		 *         "period_of_report": "2023-09-30",
		 *         "url": "https://www.sec.gov/Archives/edgar/data/320193/000032019323000077/aapl-20230930.htm"
		 *       },
		 *       "filing_id": "123e4567-e89b-12d3-a456-426614174001",
		 *       "id": "123e4567-e89b-12d3-a456-426614174002",
		 *       "title": "10-K Annual Report"
		 *     }
		 */
		DocumentResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the document
			 */
			id: string;
			/**
			 * Filing Id
			 * @description ID of the filing this document belongs to
			 */
			filing_id?: string | null;
			/**
			 * Company Ticker
			 * @description ID of the company this document belongs to
			 */
			company_ticker: string;
			/**
			 * Title
			 * @description Name of the document
			 */
			title: string;
			/**
			 * Document Type
			 * @description Type of the document
			 */
			document_type: string;
			/**
			 * Content
			 * @description Text content of the document
			 */
			content?: string | null;
			/** @description Filing information including SEC URL */
			filing?: components['schemas']['FilingResponse'] | null;
			/**
			 * Content Hash
			 * @description SHA256 hash of the content
			 */
			content_hash?: string | null;
			/**
			 * Short Hash
			 * @description Shortened version of content hash for URLs
			 */
			short_hash?: string | null;
		};
		/**
		 * FilingResponse
		 * @description Response schema for a filing.
		 * @example {
		 *       "accession_number": "0000320193-23-000077",
		 *       "company_id": "123e4567-e89b-12d3-a456-426614174000",
		 *       "filing_date": "2023-11-03",
		 *       "form": "10-K",
		 *       "id": "123e4567-e89b-12d3-a456-426614174001",
		 *       "period_of_report": "2023-09-30",
		 *       "url": "https://www.sec.gov/Archives/edgar/data/320193/000032019323000077/aapl-20230930.htm"
		 *     }
		 */
		FilingResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the filing
			 */
			id: string;
			/**
			 * Company Id
			 * Format: uuid
			 * @description ID of the company this filing belongs to
			 */
			company_id: string;
			/**
			 * Accession Number
			 * @description SEC accession number
			 */
			accession_number: string;
			/**
			 * Form
			 * @description SEC filing type (e.g., 10-K, 10-Q)
			 */
			form: string;
			/**
			 * Filing Date
			 * Format: date
			 * @description Date the filing was submitted
			 */
			filing_date: string;
			/**
			 * Url
			 * @description URL to the filing on SEC website
			 */
			url?: string | null;
			/**
			 * Period Of Report
			 * @description Period covered by the report
			 */
			period_of_report?: string | null;
		};
		/**
		 * GeneratedContentResponse
		 * @description Response schema for generated content (consolidates Aggregate and Completion).
		 * @example {
		 *       "company_id": "123e4567-e89b-12d3-a456-426614174000",
		 *       "content": "This comprehensive analysis of the company's financial performance...",
		 *       "content_hash": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2",
		 *       "created_at": "2023-12-25T12:30:45.123456",
		 *       "description": "foo",
		 *       "document_type": "MDA",
		 *       "id": "123e4567-e89b-12d3-a456-426614174007",
		 *       "model_config_id": "123e4567-e89b-12d3-a456-426614174006",
		 *       "short_hash": "a1b2c3d4e5f6",
		 *       "source_content_ids": [],
		 *       "source_document_ids": [
		 *         "123e4567-e89b-12d3-a456-426614174002"
		 *       ],
		 *       "source_type": "documents",
		 *       "summary": "Key insights from financial analysis...",
		 *       "system_prompt_id": "123e4567-e89b-12d3-a456-426614174003",
		 *       "total_duration": 3.8
		 *     }
		 */
		GeneratedContentResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the generated content
			 */
			id: string;
			/**
			 * Content Hash
			 * @description SHA256 hash of the content
			 */
			content_hash?: string | null;
			/**
			 * Short Hash
			 * @description Shortened hash for URLs (first 12 characters)
			 */
			short_hash?: string | null;
			/**
			 * Company Id
			 * @description ID of the company this content belongs to
			 */
			company_id?: string | null;
			/**
			 * Description
			 * @description Content description
			 */
			description?: string | null;
			/**
			 * Document Type
			 * @description Type of document (e.g., MDA, RISK_FACTORS, DESCRIPTION)
			 */
			document_type?: string | null;
			/**
			 * Source Type
			 * @description Type of sources used (documents, generated_content, both)
			 */
			source_type: string;
			/**
			 * Created At
			 * Format: date-time
			 * @description Timestamp when the content was created
			 */
			created_at: string;
			/**
			 * Total Duration
			 * @description Total duration of content generation in seconds
			 */
			total_duration?: number | null;
			/**
			 * Input Tokens
			 * @description Number of input tokens used for generation
			 */
			input_tokens?: number | null;
			/**
			 * Output Tokens
			 * @description Number of output tokens produced during generation
			 */
			output_tokens?: number | null;
			/**
			 * Form Type
			 * @description SEC form type associated with source documents
			 */
			form_type?: string | null;
			/**
			 * Warning
			 * @description Warning message if any issues occurred during generation
			 */
			warning?: string | null;
			/**
			 * Content
			 * @description The actual AI-generated content
			 */
			content?: string | null;
			/**
			 * Summary
			 * @description Generated summary of the content
			 */
			summary?: string | null;
			/**
			 * Model Config Id
			 * @description ID of the model configuration used
			 */
			model_config_id?: string | null;
			/**
			 * System Prompt Id
			 * @description ID of the system prompt used
			 */
			system_prompt_id?: string | null;
			/**
			 * User Prompt Id
			 * @description ID of the user prompt used
			 */
			user_prompt_id?: string | null;
			/**
			 * Source Document Ids
			 * @description List of source document IDs
			 */
			source_document_ids?: string[];
			/**
			 * Source Content Ids
			 * @description List of source content IDs
			 */
			source_content_ids?: string[];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/**
		 * JobCreateRequest
		 * @description Request schema for submitting a job.
		 */
		JobCreateRequest: {
			/**
			 * Job Type
			 * @description Job type (e.g., company_ingestion, test)
			 */
			job_type: string;
			/**
			 * Params
			 * @description Job parameters as JSON
			 */
			params?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Priority
			 * @description Priority (0=critical, 4=backlog)
			 * @default 2
			 */
			priority: number;
			/**
			 * Max Retries
			 * @description Maximum retry attempts
			 * @default 3
			 */
			max_retries: number;
		};
		/**
		 * JobResponse
		 * @description Response schema for a job.
		 */
		JobResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique job identifier
			 */
			id: string;
			/**
			 * Job Type
			 * @description Job type
			 */
			job_type: string;
			/**
			 * Params
			 * @description Job parameters
			 */
			params?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Priority
			 * @description Priority (lower = higher)
			 */
			priority: number;
			/**
			 * Status
			 * @description Job status
			 */
			status: string;
			/**
			 * Worker Id
			 * @description Worker that claimed the job
			 */
			worker_id?: string | null;
			/**
			 * Created At
			 * @description When the job was created
			 */
			created_at?: string | null;
			/**
			 * Updated At
			 * @description Last update timestamp
			 */
			updated_at?: string | null;
			/**
			 * Started At
			 * @description When execution began
			 */
			started_at?: string | null;
			/**
			 * Completed At
			 * @description When execution finished
			 */
			completed_at?: string | null;
			/**
			 * Retry Count
			 * @description Current retry count
			 * @default 0
			 */
			retry_count: number;
			/**
			 * Max Retries
			 * @description Maximum retries allowed
			 * @default 3
			 */
			max_retries: number;
			/**
			 * Result
			 * @description Job result payload
			 */
			result?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Error
			 * @description Error message if failed
			 */
			error?: string | null;
			/**
			 * Duration
			 * @description Execution duration in seconds
			 */
			duration?: number | null;
		};
		/**
		 * ModelConfigResponse
		 * @description Response schema for a model configuration.
		 * @example {
		 *       "created_at": "2023-12-25T12:30:45.123456",
		 *       "id": "123e4567-e89b-12d3-a456-426614174006",
		 *       "model": "llama3.2:3b",
		 *       "num_ctx": 4096,
		 *       "num_gpu": 1,
		 *       "num_predict": -1,
		 *       "options": {
		 *         "num_ctx": 4096,
		 *         "temperature": 0.8
		 *       },
		 *       "seed": 42,
		 *       "temperature": 0.8,
		 *       "top_k": 40,
		 *       "top_p": 0.9
		 *     }
		 */
		ModelConfigResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the model config
			 */
			id: string;
			/**
			 * Model
			 * @description Model name
			 */
			model: string;
			/**
			 * Created At
			 * Format: date-time
			 * @description Timestamp when the config was created
			 */
			created_at: string;
			/**
			 * Options
			 * @description Ollama options as JSON
			 */
			options?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Num Ctx
			 * @description Context window size
			 */
			num_ctx?: number | null;
			/**
			 * Temperature
			 * @description Temperature parameter
			 */
			temperature?: number | null;
			/**
			 * Top K
			 * @description Top-k parameter
			 */
			top_k?: number | null;
			/**
			 * Top P
			 * @description Top-p parameter
			 */
			top_p?: number | null;
			/**
			 * Seed
			 * @description Random seed
			 */
			seed?: number | null;
			/**
			 * Num Predict
			 * @description Number of tokens to predict
			 */
			num_predict?: number | null;
			/**
			 * Num Gpu
			 * @description Number of GPUs to use
			 */
			num_gpu?: number | null;
		};
		/**
		 * PipelineRunResponse
		 * @description Response schema for a pipeline run.
		 */
		PipelineRunResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Pipeline run identifier
			 */
			id: string;
			/**
			 * Company Id
			 * Format: uuid
			 * @description Company this run belongs to
			 */
			company_id: string;
			/**
			 * Trigger
			 * @description How the run was initiated (manual, scheduled)
			 */
			trigger: string;
			/**
			 * Status
			 * @description Run status
			 */
			status: string;
			/**
			 * Forms
			 * @description SEC forms requested
			 */
			forms?: string[] | null;
			/**
			 * Started At
			 * @description When the run started
			 */
			started_at?: string | null;
			/**
			 * Completed At
			 * @description When the run finished
			 */
			completed_at?: string | null;
			/**
			 * Error
			 * @description Error message if failed
			 */
			error?: string | null;
			/**
			 * Jobs Created
			 * @description Number of jobs created
			 * @default 0
			 */
			jobs_created: number;
			/**
			 * Jobs Completed
			 * @description Number of jobs completed
			 * @default 0
			 */
			jobs_completed: number;
			/**
			 * Jobs Failed
			 * @description Number of jobs failed
			 * @default 0
			 */
			jobs_failed: number;
			/**
			 * Run Metadata
			 * @description Arbitrary metadata
			 */
			run_metadata?: {
				[key: string]: unknown;
			} | null;
		};
		/**
		 * PipelineStatusResponse
		 * @description Dashboard overview of all pipeline runs.
		 */
		PipelineStatusResponse: {
			/**
			 * Total Companies
			 * @description Total tracked companies
			 */
			total_companies: number;
			/**
			 * Companies With Failures
			 * @description Companies with consecutive failures
			 * @default 0
			 */
			companies_with_failures: number;
			/**
			 * Stale Runs
			 * @description Runs stuck in RUNNING state
			 * @default 0
			 */
			stale_runs: number;
			/**
			 * Next Poll Seconds
			 * @description Estimated seconds until next poll
			 */
			next_poll_seconds?: number | null;
			/**
			 * Companies
			 * @description Per-company status
			 */
			companies?: components['schemas']['CompanyPipelineStatus'][];
		};
		/**
		 * PipelineTriggerRequest
		 * @description Request to manually trigger a pipeline run.
		 */
		PipelineTriggerRequest: {
			/**
			 * Forms
			 * @description SEC forms to process (defaults to scheduler config)
			 */
			forms?: string[] | null;
		};
		/**
		 * PromptResponse
		 * @description Response schema for a prompt.
		 * @example {
		 *       "content": "Analyze the financial statements for the company, focusing on key metrics and trends.",
		 *       "description": "Analyzes financial statements from SEC filings",
		 *       "id": "123e4567-e89b-12d3-a456-426614174003",
		 *       "name": "Financial Statement Analysis",
		 *       "role": "system"
		 *     }
		 */
		PromptResponse: {
			/**
			 * Id
			 * Format: uuid
			 * @description Unique identifier for the prompt
			 */
			id: string;
			/**
			 * Name
			 * @description Name of the prompt
			 */
			name: string;
			/**
			 * Description
			 * @description Description of the prompt
			 */
			description?: string | null;
			/**
			 * Role
			 * @description Role of the prompt (system, assistant, user)
			 */
			role: string;
			/**
			 * Content
			 * @description Prompt content text
			 */
			content: string;
		};
		/**
		 * SearchResponse
		 * @description Response for unified search endpoint.
		 */
		SearchResponse: {
			/**
			 * Results
			 * @description Search result items
			 */
			results?: components['schemas']['SearchResultItem'][];
			/**
			 * Total
			 * @description Total number of matching results
			 */
			total: number;
			/**
			 * Query
			 * @description The search query that was executed
			 */
			query: string;
		};
		/**
		 * SearchResultItem
		 * @description A single search result from unified search.
		 */
		SearchResultItem: {
			/**
			 * Entity Type
			 * @description Type of entity: company, filing, or generated_content
			 */
			entity_type: string;
			/**
			 * Id
			 * Format: uuid
			 * @description Entity ID
			 */
			id: string;
			/**
			 * Rank
			 * @description Relevance ranking score
			 */
			rank: number;
			/**
			 * Headline
			 * @description Highlighted search result snippet
			 */
			headline?: string | null;
			/**
			 * Title
			 * @description Primary display text (name, form type, description)
			 */
			title?: string | null;
			/**
			 * Subtitle
			 * @description Secondary text (ticker, accession number)
			 */
			subtitle?: string | null;
			/**
			 * Date Value
			 * @description Associated date (filing_date, created_at)
			 */
			date_value?: string | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	search_companies_partial_companies_search_get: {
		parameters: {
			query: {
				/** @description Search query for company name or ticker */
				query: string;
				/** @description Maximum number of results to return */
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyResponse'][];
				};
			};
			/** @description Bad request - missing required parameters */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_company_by_id_route_companies_id__company_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				company_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyResponse'];
				};
			};
			/** @description Company not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_company_by_ticker_route_companies_by_ticker__ticker__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ticker: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyResponse'];
				};
			};
			/** @description Company not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_companies_route_companies_get: {
		parameters: {
			query?: {
				/** @description Search query for company name or ticker */
				search?: string | null;
				/** @description Number of companies to skip */
				skip?: number;
				/** @description Maximum number of companies to return */
				limit?: number;
				/** @description Company ticker symbol */
				ticker?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyResponse'][];
				};
			};
			/** @description Bad request - invalid parameters */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_document_by_id_documents__document_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				document_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DocumentResponse'];
				};
			};
			/** @description Document not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_document_content_documents__document_id__content_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				document_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/plain': string;
				};
			};
			/** @description Document not found or has no content */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_documents_by_filing_id_documents_by_filing__filing_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				filing_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DocumentResponse'][];
				};
			};
			/** @description Filing not found or has no documents */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_documents_by_ids_documents_by_ids_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': string[];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DocumentResponse'][];
				};
			};
			/** @description Invalid input or UUIDs */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_document_by_accession_and_hash_documents_by_accession__accession_number___content_hash__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accession_number: string;
				content_hash: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DocumentResponse'];
				};
			};
			/** @description Document not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_company_filings_filings_by_company__company_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				company_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['FilingResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_filings_by_ticker_filings_by_ticker__ticker__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ticker: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['FilingResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_filing_by_accession_filings__accession_number__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accession_number: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['FilingResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_filing_documents_by_accession_filings__accession_number__documents_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accession_number: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DocumentResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_filing_company_by_accession_filings__accession_number__company_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accession_number: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CompanyResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_prompt_by_id_prompts__prompt_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				prompt_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PromptResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_company_generated_content_by_ticker_generated_content_by_ticker__ticker__get: {
		parameters: {
			query?: {
				limit?: number;
			};
			header?: never;
			path: {
				ticker: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GeneratedContentResponse'][];
				};
			};
			/** @description Company not found or has no generated content */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_aggregate_summaries_by_ticker_route_generated_content_aggregate_summaries_by_ticker__ticker__get: {
		parameters: {
			query?: {
				limit?: number;
			};
			header?: never;
			path: {
				ticker: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GeneratedContentResponse'][];
				};
			};
			/** @description Company not found or has no aggregate summaries */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_generated_content_by_ticker_and_hash_generated_content_by_ticker__ticker___content_hash__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ticker: string;
				content_hash: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GeneratedContentResponse'];
				};
			};
			/** @description Generated content not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_generated_content_by_id_generated_content__content_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				content_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GeneratedContentResponse'];
				};
			};
			/** @description Generated content not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_generated_content_by_hash_only_generated_content_by_hash__content_hash__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				content_hash: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GeneratedContentResponse'];
				};
			};
			/** @description Generated content not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_generated_content_sources_generated_content__content_id__sources_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				content_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
			/** @description Generated content not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_jobs_route_jobs_get: {
		parameters: {
			query?: {
				/** @description Filter by status */
				status?: string | null;
				/** @description Filter by job type */
				job_type?: string | null;
				limit?: number;
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	enqueue_job_jobs_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobResponse'];
				};
			};
			/** @description Invalid job type or parameters */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_job_by_id_jobs__job_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobResponse'];
				};
			};
			/** @description Job not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	cancel_job_route_jobs__job_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobResponse'];
				};
			};
			/** @description Job not found or not cancellable */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_all_model_configs_model_configs__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ModelConfigResponse'][];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_model_config_by_id_model_configs__config_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				config_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ModelConfigResponse'];
				};
			};
			/** @description Model configuration not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	get_model_config_by_model_name_model_configs_by_name__model_name__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				model_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ModelConfigResponse'];
				};
			};
			/** @description Model configuration not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	list_runs_pipeline_runs_get: {
		parameters: {
			query?: {
				/** @description Filter by status */
				status?: string | null;
				/** @description Filter by company ID */
				company_id?: string | null;
				limit?: number;
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineRunResponse'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_run_pipeline_runs__run_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineRunResponse'];
				};
			};
			/** @description Pipeline run not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	pipeline_status_dashboard_pipeline_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PipelineStatusResponse'];
				};
			};
		};
	};
	trigger_pipeline_pipeline_trigger__ticker__post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ticker: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/json': components['schemas']['PipelineTriggerRequest'] | null;
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
			/** @description Company not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_search_get: {
		parameters: {
			query: {
				/** @description Search query string */
				q: string;
				/** @description Entity types to search: company, filing, generated_content */
				entity_types?: string[] | null;
				/** @description Filter by SIC code */
				sic?: string | null;
				/** @description Filter by SEC form type (10-K, 10-Q) */
				form_type?: string | null;
				/** @description Filter by document type (MDA, RISK_FACTORS, etc.) */
				document_type?: string | null;
				/** @description Filter results from this date */
				date_from?: string | null;
				/** @description Filter results up to this date */
				date_to?: string | null;
				/** @description Maximum results to return */
				limit?: number;
				/** @description Offset for pagination */
				offset?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Bad request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	root_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
		};
	};
}
