"""add_generated_content_id_to_ratings

Revision ID: ab088f8a36be
Revises: 147f0cde7694
Create Date: 2025-08-04 13:42:23.427469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab088f8a36be'
down_revision: Union[str, Sequence[str], None] = '147f0cde7694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('generated_content_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ratings_generated_content_id'), 'ratings', ['generated_content_id'], unique=False)
    op.create_foreign_key(None, 'ratings', 'generated_content', ['generated_content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_index(op.f('ix_ratings_generated_content_id'), table_name='ratings')
    op.drop_column('ratings', 'generated_content_id')
    # ### end Alembic commands ###
