up: _load_images
    ~/.local/bin/nerdctl compose -f symbology/docker-compose.yaml --env-file symbology/.env up -d

down:
    ~/.local/bin/nerdctl compose -f symbology/docker-compose.yaml down

logs *ARGS:
    ~/.local/bin/nerdctl compose -f symbology/docker-compose.yaml logs {{ARGS}}

_load_images:
    ~/.local/bin/nerdctl load -i symbology/images/symbology-api-latest.tar
    ~/.local/bin/nerdctl load -i symbology/images/symbology-ui-latest.tar
    ~/.local/bin/nerdctl load -i symbology/images/postgres-17.4.tar