<script lang="ts">
	import { ChevronRight, Sparkles } from '@lucide/svelte';
	import { titleCase } from 'title-case';
	import BrowseList from '$lib/components/BrowseList.svelte';
	import { SvelteURLSearchParams } from 'svelte/reactivity';
	import { formatDate } from '$lib/utils/filings';
	import { stageMeta, synthesisLevel } from '$lib/utils/synthesis';
	import type { SynthesisListItem, SynthesisListResponse } from '$lib/api-types';

	async function fetchPage(skip: number, limit: number, search: string) {
		const params = new SvelteURLSearchParams({ skip: String(skip), limit: String(limit) });
		if (search) params.set('search', search);
		const res = await fetch(`/api/synthesis?${params}`);
		if (!res.ok) throw new Error('Failed to fetch syntheses');
		const data: SynthesisListResponse = await res.json();
		return { items: data.syntheses, total: data.total };
	}
</script>

<svelte:head>
	<title>Synthesis - Symbology</title>
	<meta name="description" content="Browse AI syntheses generated by Symbology" />
</svelte:head>

{#snippet skeleton()}
	<div
		class="docrow grid grid-cols-[44px_1fr_24px] items-center sm:grid-cols-[56px_1fr_auto_24px]"
		aria-hidden="true"
	>
		<div><span class="block h-[18px] w-8 animate-pulse rounded bg-paper-2"></span></div>
		<div>
			<span class="block h-3.5 w-1/2 animate-pulse rounded bg-paper-2"></span>
			<span class="mt-1.5 block h-2.5 w-1/3 animate-pulse rounded bg-paper-2"></span>
		</div>
		<div class="hidden sm:block">
			<span class="block h-5 w-20 animate-pulse rounded bg-paper-2"></span>
		</div>
		<span class="block h-3.5 w-3.5 animate-pulse rounded bg-paper-2"></span>
	</div>
{/snippet}

{#snippet row(s: SynthesisListItem)}
	{@const level = synthesisLevel(s.generation_depth)}
	{@const noun = stageMeta(s.content_stage).noun}
	<a
		href="/s/{s.short_hash}"
		class="docrow grid grid-cols-[44px_1fr_24px] items-center text-inherit no-underline sm:grid-cols-[56px_1fr_auto_24px]"
	>
		<div>
			<span class="inline-flex items-center gap-1 font-mono text-[11px] font-medium text-teal-2">
				<Sparkles size={12} strokeWidth={2} />
				{level || 'S'}
			</span>
		</div>
		<div>
			<div class="text-sm font-medium text-ink">
				{titleCase(s.scope_label.toLowerCase())}
			</div>
			<div class="mt-0.5 font-mono text-xs text-ink-4">
				{#if s.scope_ticker}{s.scope_ticker}&nbsp;&middot;&nbsp;{/if}{noun}{#if s.created_at}&nbsp;&middot;&nbsp;{formatDate(
						s.created_at
					)}{/if}
			</div>
		</div>
		<div class="hidden sm:flex sm:justify-end">
			{#if s.form_type}
				<span class="tag">{s.form_type}</span>
			{/if}
		</div>
		<ChevronRight class="h-3.5 w-3.5 text-ink-4" />
	</a>
{/snippet}

<BrowseList
	{fetchPage}
	{row}
	{skeleton}
	allLabel="All syntheses"
	searchPlaceholder="Company name or ticker..."
	emptyLabel="No syntheses found."
/>
