"""add jobs table

Revision ID: 481ecc895dd9
Revises: bfea649a1a3c
Create Date: 2026-02-06 00:04:35.696941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '481ecc895dd9'
down_revision: Union[str, Sequence[str], None] = 'bfea649a1a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('COMPANY_INGESTION', 'FILING_INGESTION', 'CONTENT_GENERATION', 'INGEST_PIPELINE', 'TEST', name='job_type_enum'), nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status_enum'), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_queue_poll', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_jobs_stale_detection', 'jobs', ['status', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_stale_detection', table_name='jobs')
    op.drop_index('ix_jobs_queue_poll', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
