"""initial schema

Revision ID: bfea649a1a3c
Revises: 
Create Date: 2026-02-05 22:38:04.926218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfea649a1a3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exchanges', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sic', sa.String(length=4), nullable=True),
    sa.Column('sic_description', sa.String(length=255), nullable=True),
    sa.Column('fiscal_year_end', sa.Date(), nullable=True),
    sa.Column('former_names', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_sic'), 'companies', ['sic'], unique=False)
    op.create_table('financial_concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_concepts_name'), 'financial_concepts', ['name'], unique=True)
    op.create_table('model_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_content_hash'), 'model_configs', ['content_hash'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('SYSTEM', 'ASSISTANT', 'USER', name='promptrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_content_hash'), 'prompts', ['content_hash'], unique=True)
    op.create_table('filings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('accession_number', sa.String(length=20), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_accession_number'), 'filings', ['accession_number'], unique=True)
    op.create_index(op.f('ix_filings_company_id'), 'filings', ['company_id'], unique=False)
    op.create_index(op.f('ix_filings_filing_date'), 'filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_filings_form'), 'filings', ['form'], unique=False)
    op.create_index(op.f('ix_filings_period_of_report'), 'filings', ['period_of_report'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Enum('MDA', 'RISK_FACTORS', 'DESCRIPTION', 'CONTROLS_PROCEDURES', 'LEGAL_PROCEEDINGS', 'MARKET_RISK', 'EXECUTIVE_COMPENSATION', 'DIRECTORS_OFFICERS', name='document_type_enum'), nullable=True),
    sa.Column('form_type', sa.String(length=10), nullable=True),
    sa.Column('source_type', sa.Enum('DOCUMENTS', 'GENERATED_CONTENT', 'BOTH', name='content_source_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_config_id', sa.Uuid(), nullable=True),
    sa.Column('system_prompt_id', sa.Uuid(), nullable=True),
    sa.Column('user_prompt_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_company_id'), 'generated_content', ['company_id'], unique=False)
    op.create_index(op.f('ix_generated_content_content_hash'), 'generated_content', ['content_hash'], unique=True)
    op.create_index(op.f('ix_generated_content_document_type'), 'generated_content', ['document_type'], unique=False)
    op.create_index(op.f('ix_generated_content_form_type'), 'generated_content', ['form_type'], unique=False)
    op.create_index(op.f('ix_generated_content_model_config_id'), 'generated_content', ['model_config_id'], unique=False)
    op.create_index(op.f('ix_generated_content_system_prompt_id'), 'generated_content', ['system_prompt_id'], unique=False)
    op.create_index(op.f('ix_generated_content_user_prompt_id'), 'generated_content', ['user_prompt_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('MDA', 'RISK_FACTORS', 'DESCRIPTION', 'CONTROLS_PROCEDURES', 'LEGAL_PROCEEDINGS', 'MARKET_RISK', 'EXECUTIVE_COMPENSATION', 'DIRECTORS_OFFICERS', name='document_type_enum'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_filing_id'), 'documents', ['filing_id'], unique=False)
    op.create_table('financial_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('filing_id', sa.Uuid(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['financial_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_values_company_id'), 'financial_values', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_values_concept_id'), 'financial_values', ['concept_id'], unique=False)
    op.create_index(op.f('ix_financial_values_filing_id'), 'financial_values', ['filing_id'], unique=False)
    op.create_index(op.f('ix_financial_values_value_date'), 'financial_values', ['value_date'], unique=False)
    op.create_table('generated_content_source_association',
    sa.Column('parent_content_id', sa.Uuid(), nullable=False),
    sa.Column('source_content_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_content_id'], ['generated_content.id'], ),
    sa.ForeignKeyConstraint(['source_content_id'], ['generated_content.id'], ),
    sa.PrimaryKeyConstraint('parent_content_id', 'source_content_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_content_id', sa.Uuid(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('format_score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_generated_content_id'), 'ratings', ['generated_content_id'], unique=False)
    op.create_table('generated_content_document_association',
    sa.Column('generated_content_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ),
    sa.PrimaryKeyConstraint('generated_content_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_content_document_association')
    op.drop_index(op.f('ix_ratings_generated_content_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_table('generated_content_source_association')
    op.drop_index(op.f('ix_financial_values_value_date'), table_name='financial_values')
    op.drop_index(op.f('ix_financial_values_filing_id'), table_name='financial_values')
    op.drop_index(op.f('ix_financial_values_concept_id'), table_name='financial_values')
    op.drop_index(op.f('ix_financial_values_company_id'), table_name='financial_values')
    op.drop_table('financial_values')
    op.drop_index(op.f('ix_documents_filing_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_generated_content_user_prompt_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_system_prompt_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_model_config_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_form_type'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_document_type'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_content_hash'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_company_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_filings_period_of_report'), table_name='filings')
    op.drop_index(op.f('ix_filings_form'), table_name='filings')
    op.drop_index(op.f('ix_filings_filing_date'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_accession_number'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_prompts_content_hash'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_model_configs_content_hash'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_financial_concepts_name'), table_name='financial_concepts')
    op.drop_table('financial_concepts')
    op.drop_index(op.f('ix_companies_sic'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
