@hostname = localhost
@port = 8000

# API Health Endpoint
GET http://{{hostname}}:{{port}}/

###

# Get Company with just Ticker
GET http://{{hostname}}:{{port}}/api/companies
content-type: application/json

{
  "ticker": "MSFT"
}


###

# Create Company with just Ticker
# handler -> check db -> edgar -> write db (if company wasn't already in db)
POST http://{{hostname}}:{{port}}/api/companies
content-type: application/json

{
  "ticker": "MSFT"
}

###
