# shellcheck shell=bash
# shellcheck disable=SC2035,SC2050,SC2148

generate-api-types:
    node scripts/generate-api-types.js

# Production build with quality checks
build:
    npm run build:prod
    nerdctl build . -t symbology-ui:latest