# shellcheck shell=bash
# shellcheck disable=SC2148,SC2035,SC1083

deps:
    uv pip compile pyproject.toml -o requirements.lock
    uv pip install -r requirements.lock

run-api *ARGS: _create_venv
    uv run -m src.api.main "{{ARGS}}"

run-ingest *ARGS: # Run with defaults (AAPL, 2022)
    uv run -m src.ingestion.main {{ARGS}} 2>&1 | tee ingest.log

# summarize:
#     uv run run.py summarize --document-id 3 --template-id 2 --temperature 0.7

# test and lint outputs are logged to make it easy to include as llm context
test-python *ARGS: _create_venv
    uv run -m pytest --cov=src.database --cov=src.ingestion --cov=src.api src/tests/ --json-report --json-report-file=test.log {{ARGS}}

lint-python *FLAGS: # lint --fix
    ~/.local/share/nvim/mason/bin/ruff check src {{FLAGS}} | tee lint.log
