"""Tests for the generated content API endpoints."""
from datetime import datetime
from unittest.mock import MagicMock, patch

from fastapi.testclient import TestClient
from symbology.api.main import create_app
from uuid_extensions import uuid7

client = TestClient(create_app())

# Sample test data
SAMPLE_CONTENT_ID = uuid7()
SAMPLE_COMPANY_ID = uuid7()
SAMPLE_DOCUMENT_ID = uuid7()
SAMPLE_MODEL_CONFIG_ID = uuid7()
SAMPLE_PROMPT_ID = uuid7()

SAMPLE_GENERATED_CONTENT = {
    "id": str(SAMPLE_CONTENT_ID),
    "content_hash": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2",
    "short_hash": "a1b2c3d4e5f6",
    "company_id": str(SAMPLE_COMPANY_ID),
    "document_type": "MDA",
    "source_type": "documents",
    "created_at": datetime.now().isoformat(),
    "total_duration": 3.8,
    "content": "This is a comprehensive analysis of the company's Management Discussion and Analysis section, highlighting key financial metrics and business performance indicators.",  # noqa: E501
    "summary": "Key insights from MDA analysis including revenue growth, operational challenges, and strategic initiatives.",
    "model_config_id": str(SAMPLE_MODEL_CONFIG_ID),
    "system_prompt_id": str(SAMPLE_PROMPT_ID),
    "user_prompt_id": None,
    "source_document_ids": [str(SAMPLE_DOCUMENT_ID)],
    "source_content_ids": []
}

SAMPLE_GENERATED_CONTENT_LIST = [
    SAMPLE_GENERATED_CONTENT,
    {
        "id": str(uuid7()),
        "content_hash": "b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3",
        "short_hash": "b2c3d4e5f6g7",
        "company_id": str(SAMPLE_COMPANY_ID),
        "document_type": "RISK_FACTORS",
        "source_type": "documents",
        "created_at": datetime.now().isoformat(),
        "total_duration": 2.1,
        "content": "Analysis of risk factors affecting the company's business operations and financial performance.",
        "summary": "Key risk factors including market volatility, regulatory changes, and competitive pressures.",
        "model_config_id": str(SAMPLE_MODEL_CONFIG_ID),
        "system_prompt_id": str(SAMPLE_PROMPT_ID),
        "user_prompt_id": None,
        "source_document_ids": [str(uuid7())],
        "source_content_ids": []
    }
]

SAMPLE_CREATE_REQUEST = {
    "company_id": str(SAMPLE_COMPANY_ID),
    "document_type": "MDA",
    "source_type": "documents",
    "content": "New analysis content generated by AI.",
    "summary": "Summary of the new analysis.",
    "model_config_id": str(SAMPLE_MODEL_CONFIG_ID),
    "system_prompt_id": str(SAMPLE_PROMPT_ID),
    "source_document_ids": [str(SAMPLE_DOCUMENT_ID)],
    "total_duration": 4.2
}


class TestGeneratedContentAPI:
    """Test class for Generated Content API endpoints."""

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    def test_get_company_generated_content_by_ticker_success(self, mock_get_recent):
        """Test successful retrieval of generated content by ticker."""
        # Mock the database function to return sample data
        mock_content_objects = []
        for content_data in SAMPLE_GENERATED_CONTENT_LIST:
            mock_obj = MagicMock()
            mock_obj.to_dict.return_value = content_data
            mock_content_objects.append(mock_obj)

        mock_get_recent.return_value = mock_content_objects

        # Make the API call
        response = client.get("/generated-content/by-ticker/AAPL?limit=10")

        # Assertions
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 2
        assert data[0]["id"] == str(SAMPLE_CONTENT_ID)
        assert data[0]["document_type"] == "MDA"
        assert data[1]["document_type"] == "RISK_FACTORS"

        # Verify the mock was called correctly
        mock_get_recent.assert_called_once_with("AAPL", 10)

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    def test_get_company_generated_content_by_ticker_not_found(self, mock_get_recent):
        """Test retrieval when no content found for ticker."""
        mock_get_recent.return_value = []

        response = client.get("/generated-content/by-ticker/NONEXIST")

        assert response.status_code == 404
        assert "No generated content found" in response.json()["detail"]
        mock_get_recent.assert_called_once_with("NONEXIST", 10)

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    def test_get_company_generated_content_by_ticker_server_error(self, mock_get_recent):
        """Test handling of server errors."""
        mock_get_recent.side_effect = Exception("Database error")

        response = client.get("/generated-content/by-ticker/AAPL")

        assert response.status_code == 500
        assert "Internal server error" in response.json()["detail"]

    @patch("symbology.api.routes.generated_content.get_generated_content_by_company_and_ticker")
    def test_get_generated_content_by_ticker_and_hash_success(self, mock_get_by_ticker_hash):
        """Test successful retrieval by ticker and hash."""
        mock_content = MagicMock()
        mock_content.to_dict.return_value = SAMPLE_GENERATED_CONTENT
        mock_get_by_ticker_hash.return_value = mock_content

        response = client.get("/generated-content/by-ticker/AAPL/a1b2c3d4e5f6")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == str(SAMPLE_CONTENT_ID)
        assert data["short_hash"] == "a1b2c3d4e5f6"
        mock_get_by_ticker_hash.assert_called_once_with("AAPL", "a1b2c3d4e5f6")

    @patch("symbology.api.routes.generated_content.get_generated_content_by_company_and_ticker")
    def test_get_generated_content_by_ticker_and_hash_not_found(self, mock_get_by_ticker_hash):
        """Test retrieval when content not found by ticker and hash."""
        mock_get_by_ticker_hash.return_value = None

        response = client.get("/generated-content/by-ticker/AAPL/nonexistent")

        assert response.status_code == 404
        assert "Generated content not found" in response.json()["detail"]

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_by_id_success(self, mock_get_content):
        """Test successful retrieval by content ID."""
        mock_content = MagicMock()
        mock_content.to_dict.return_value = SAMPLE_GENERATED_CONTENT
        mock_get_content.return_value = mock_content

        response = client.get(f"/generated-content/{SAMPLE_CONTENT_ID}")

        assert response.status_code == 200
        data = response.json()
        assert data["id"] == str(SAMPLE_CONTENT_ID)
        mock_get_content.assert_called_once_with(SAMPLE_CONTENT_ID)

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_by_id_not_found(self, mock_get_content):
        """Test retrieval when content not found by ID."""
        mock_get_content.return_value = None
        non_existent_id = uuid7()

        response = client.get(f"/generated-content/{non_existent_id}")

        assert response.status_code == 404
        assert f"Generated content not found with ID: {non_existent_id}" in response.json()["detail"]

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_by_id_invalid_uuid(self, mock_get_content):
        """Test handling of invalid UUID format."""
        response = client.get("/generated-content/invalid-uuid")

        assert response.status_code == 422  # Validation error
        # FastAPI automatically handles UUID validation

    @patch("symbology.api.routes.generated_content.get_generated_content_by_hash")
    def test_get_generated_content_by_hash_success(self, mock_get_by_hash):
        """Test successful retrieval by content hash."""
        mock_content = MagicMock()
        mock_content.to_dict.return_value = SAMPLE_GENERATED_CONTENT
        mock_get_by_hash.return_value = mock_content

        response = client.get("/generated-content/by-hash/a1b2c3d4e5f6")

        assert response.status_code == 200
        data = response.json()
        assert data["content_hash"] == "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2"
        mock_get_by_hash.assert_called_once_with("a1b2c3d4e5f6")

    @patch("symbology.api.routes.generated_content.get_generated_content_by_hash")
    def test_get_generated_content_by_hash_not_found(self, mock_get_by_hash):
        """Test retrieval when content not found by hash."""
        mock_get_by_hash.return_value = None

        response = client.get("/generated-content/by-hash/nonexistent")

        assert response.status_code == 404
        assert "Generated content not found with hash" in response.json()["detail"]

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_sources_success(self, mock_get_content):
        """Test successful retrieval of content sources."""
        # Mock content with sources
        mock_content = MagicMock()
        mock_content.id = SAMPLE_CONTENT_ID

        # Mock source documents
        mock_doc = MagicMock()
        mock_doc.id = SAMPLE_DOCUMENT_ID
        mock_doc.title = "test-mda.html"
        mock_content.source_documents = [mock_doc]

        # Mock source content
        mock_source_content = MagicMock()
        mock_source_content.id = uuid7()
        mock_source_content.get_short_hash.return_value = "xyz123456789"
        mock_source_content.description = "RISK_FACTORS"
        mock_content.source_content = [mock_source_content]

        mock_get_content.return_value = mock_content

        response = client.get(f"/generated-content/{SAMPLE_CONTENT_ID}/sources")

        assert response.status_code == 200
        data = response.json()

        # Verify source documents
        assert "source_documents" in data
        assert len(data["source_documents"]) == 1
        assert data["source_documents"][0]["id"] == str(SAMPLE_DOCUMENT_ID)
        assert data["source_documents"][0]["name"] == "test-mda.html"
        assert data["source_documents"][0]["type"] == "document"

        # Verify source content
        assert "source_content" in data
        assert len(data["source_content"]) == 1
        assert data["source_content"][0]["short_hash"] == "xyz123456789"
        assert data["source_content"][0]["description"] == "RISK_FACTORS"
        assert data["source_content"][0]["type"] == "generated_content"

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_sources_not_found(self, mock_get_content):
        """Test sources retrieval when content not found."""
        mock_get_content.return_value = None
        non_existent_id = uuid7()

        response = client.get(f"/generated-content/{non_existent_id}/sources")

        assert response.status_code == 404
        assert f"Generated content not found with ID: {non_existent_id}" in response.json()["detail"]

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_get_generated_content_sources_empty(self, mock_get_content):
        """Test sources retrieval with no sources."""
        mock_content = MagicMock()
        mock_content.id = SAMPLE_CONTENT_ID
        mock_content.source_documents = []
        mock_content.source_content = []
        mock_get_content.return_value = mock_content

        response = client.get(f"/generated-content/{SAMPLE_CONTENT_ID}/sources")

        assert response.status_code == 200
        data = response.json()
        assert data["source_documents"] == []
        assert data["source_content"] == []


class TestGeneratedContentAPIEdgeCases:
    """Test edge cases and error conditions."""

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    def test_get_content_by_ticker_with_limit(self, mock_get_recent):
        """Test limit parameter functionality."""
        mock_get_recent.return_value = []

        response = client.get("/generated-content/by-ticker/AAPL?limit=5")

        assert response.status_code == 404  # No content found
        mock_get_recent.assert_called_once_with("AAPL", 5)

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    def test_get_content_by_ticker_default_limit(self, mock_get_recent):
        """Test default limit when not specified."""
        mock_get_recent.return_value = []

        client.get("/generated-content/by-ticker/AAPL")

        mock_get_recent.assert_called_once_with("AAPL", 10)

    @patch("symbology.api.routes.generated_content.get_generated_content_by_company_and_ticker")
    def test_get_content_case_insensitive_ticker(self, mock_get_by_ticker_hash):
        """Test that ticker handling works regardless of case."""
        mock_content = MagicMock()
        mock_content.to_dict.return_value = SAMPLE_GENERATED_CONTENT
        mock_get_by_ticker_hash.return_value = mock_content

        # Test lowercase ticker
        response = client.get("/generated-content/by-ticker/aapl/a1b2c3d4e5f6")

        assert response.status_code == 200
        # The actual case handling is done in the database layer
        mock_get_by_ticker_hash.assert_called_once_with("aapl", "a1b2c3d4e5f6")

    @patch("symbology.api.routes.generated_content.get_generated_content")
    def test_sources_endpoint_handles_none_document_type(self, mock_get_content):
        """Test sources endpoint handles None description gracefully."""
        mock_content = MagicMock()
        mock_content.id = SAMPLE_CONTENT_ID
        mock_content.source_documents = []

        # Mock source content with None description
        mock_source_content = MagicMock()
        mock_source_content.id = uuid7()
        mock_source_content.get_short_hash.return_value = "abc123456789"
        mock_source_content.description = None
        mock_content.source_content = [mock_source_content]

        mock_get_content.return_value = mock_content

        response = client.get(f"/generated-content/{SAMPLE_CONTENT_ID}/sources")

        assert response.status_code == 200
        data = response.json()
        assert len(data["source_content"]) == 1
        assert data["source_content"][0]["description"] is None


class TestGeneratedContentAPIIntegration:
    """Integration-style tests that verify the complete flow."""

    @patch("symbology.api.routes.generated_content.get_recent_generated_content_by_ticker")
    @patch("symbology.api.routes.generated_content.get_generated_content_by_company_and_ticker")
    def test_ticker_to_hash_workflow(self, mock_get_by_ticker_hash, mock_get_recent):
        """Test the typical workflow from ticker list to specific content."""
        # Step 1: Get recent content by ticker
        mock_content_objects = []
        for content_data in SAMPLE_GENERATED_CONTENT_LIST:
            mock_obj = MagicMock()
            mock_obj.to_dict.return_value = content_data
            mock_content_objects.append(mock_obj)

        mock_get_recent.return_value = mock_content_objects

        list_response = client.get("/generated-content/by-ticker/AAPL")
        assert list_response.status_code == 200
        content_list = list_response.json()

        # Step 2: Get specific content by hash
        first_content = content_list[0]
        short_hash = first_content["short_hash"]

        mock_content = MagicMock()
        mock_content.to_dict.return_value = SAMPLE_GENERATED_CONTENT
        mock_get_by_ticker_hash.return_value = mock_content

        detail_response = client.get(f"/generated-content/by-ticker/AAPL/{short_hash}")
        assert detail_response.status_code == 200
        detail_data = detail_response.json()
        assert detail_data["short_hash"] == short_hash

