# shellcheck shell=bash
# shellcheck disable=SC2035,SC2050,SC2148

generate-api-types:
    node scripts/generate-api-types.js

run-ui *ARGS:
    npm run dev -- --host

lint-ui *ARGS:
    npm run lint {{ARGS}} | tee ui-lint.log

# Add these commands once we set up the npm scripts
format-ui:
    npm run format

check-ui:
    npm run check | tee npm-check.log

deps-ui:
    rm -rf node_modules
    npm install

# Production build with quality checks
build-ui:
    npm run build:prod
