up:
  npm run dev -- --open --host 0.0.0.0


lint *ARGS:
        npm run lint {{ARGS}} | tee ui-lint.log

generate-api-types:
  npx openapi-typescript http://localhost:8000/openapi.json -o src/lib/generated-api-types.ts


build:
  ~/.local/bin/nerdctl build . -t symbology-ui:latest
  ~/.local/bin/nerdctl save symbology-ui:latest -o symbology-ui-latest.tar
