# shellcheck shell=bash
# shellcheck disable=SC2148,SC2035,SC1083

_create_venv:
    #!/usr/bin/env bash
    if [[ ! -d .venv ]]; then
        echo "_create_venv at $(pwd)"
        uv venv -p 3.13 .venv
        uv pip install -r requirements.lock
    fi

deps:
    uv pip compile pyproject.toml -o requirements.lock
    uv pip install -e .[dev,test]

run *ARGS: _create_venv
    uv run -m collector.api.main

ingest *ARGS: # Run with defaults (AAPL, 2022)
    uv run -m collector.bin.edgar_ingestion {{ARGS}}

generate *ARGS: # Run with defaults (AAPL, 2022)
    uv run -m collector.bin.llm_generate {{ARGS}}

logging *ARGS: # Run with defaults (AAPL, 2022)
    uv run -m collector.bin.logging {{ARGS}}

# test and lint outputs are logged to make it easy to include as llm context
test *ARGS: _create_venv
    uv run -m pytest \
      --cov=collector.api \
      --cov=collector.database \
      --cov=collector.ingestion \
      --cov=collector.llm \
      collector/tests/ {{ARGS}} | tee test.log

lint *FLAGS: # lint --fix
    ~/.local/share/nvim/mason/bin/ruff check {{FLAGS}} | tee lint.log


build:
    nerdctl build -t symbology-collector:latest .
    ~/.local/bin/nerdctl save symbology-collector:latest -o symbology-collector-latest.tar
