/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ContentSourceTypeEnum = "both" | "documents" | "generated_content";

export type ContentStageEnum = "aggregate_summary" | "change_report" | "change_report_intro" | "company_group_analysis" | "company_group_frontpage" | "company_intro" | "company_main_content" | "document_page_intro" | "filing_intro" | "filing_main_content" | "frontpage_summary" | "group_intro" | "group_main_content" | "single_summary";

export type DocumentTypeEnum = "business_description" | "controls_procedures" | "directors_officers" | "executive_compensation" | "legal_proceedings" | "management_discussion" | "market_risk" | "risk_factors";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type JobStatusEnum = "cancelled" | "completed" | "failed" | "in_progress" | "pending";

export type JobTypeEnum = "backfill_chunks" | "backfill_embeddings" | "bulk_ingest" | "company_group_pipeline" | "company_ingestion" | "content_generation" | "filing_ingestion" | "filing_page_content" | "full_pipeline" | "ingest_pipeline" | "pipeline_fan_in_check" | "pipeline_stage" | "test";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PipelineRunStatusEnum = "completed" | "failed" | "partial" | "pending" | "running";

export type PipelineTriggerEnum = "manual" | "scheduled";

export type Promptrole = "ASSISTANT" | "SYSTEM" | "USER";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AlembicVersion {
  version_num: string;
}

export interface Companies {
  cik: string | null;
  display_name: string | null;
  exchanges: string[];
  fiscal_year_end: Timestamp | null;
  former_names: Json;
  id: string;
  name: string;
  search_vector: string | null;
  sic: string | null;
  sic_description: string | null;
  ticker: string;
}

export interface CompanyGroupMembership {
  added_at: Generated<Timestamp | null>;
  company_group_id: string;
  company_id: string;
}

export interface CompanyGroups {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: string;
  name: string;
  search_vector: string | null;
  sic_codes: Generated<string[] | null>;
  slug: string;
  updated_at: Generated<Timestamp | null>;
}

export interface CompanyPageContent {
  company_id: string;
  created_at: Timestamp | null;
  id: string;
  intro_content_id: string | null;
  main_content_id: string | null;
}

export interface CompanyPageContentChangeReport {
  change_report_id: string;
  change_report_intro_id: string | null;
  company_page_content_id: string;
  document_type: DocumentTypeEnum;
}

export interface CompanyPageContentFiling {
  company_page_content_id: string;
  filing_id: string;
}

export interface DocumentChunks {
  chunk_index: number;
  content: string;
  content_hash: string | null;
  document_id: string;
  embedding: string | null;
  embedding_model: string | null;
  id: string;
}

export interface DocumentPageContent {
  created_at: Timestamp | null;
  document_id: string;
  id: string;
  intro_content_id: string | null;
  summary_content_id: string | null;
}

export interface Documents {
  company_id: string;
  content: string | null;
  content_hash: string | null;
  document_type: DocumentTypeEnum | null;
  filing_id: string | null;
  id: string;
  title: string;
}

export interface FilingPageContent {
  created_at: Timestamp | null;
  filing_id: string;
  id: string;
  intro_content_id: string | null;
  main_content_id: string | null;
}

export interface FilingPageContentDocument {
  document_id: string;
  filing_page_content_id: string;
}

export interface Filings {
  accession_number: string;
  company_id: string;
  filing_date: Timestamp;
  form: string;
  id: string;
  period_of_report: Timestamp | null;
  search_vector: string | null;
  url: string | null;
}

export interface FinancialConcepts {
  description: string | null;
  id: string;
  labels: string[];
  name: string;
}

export interface FinancialValues {
  company_id: string;
  concept_id: string;
  filing_id: string | null;
  id: string;
  value: Numeric;
  value_date: Timestamp;
}

export interface GeneratedContent {
  company_group_id: string | null;
  company_id: string | null;
  content: string | null;
  content_hash: string | null;
  content_stage: ContentStageEnum | null;
  created_at: Timestamp;
  description: string | null;
  document_id: string | null;
  document_type: DocumentTypeEnum | null;
  filing_id: string | null;
  form_type: string | null;
  generation_depth: number | null;
  id: string;
  input_tokens: number | null;
  model_config_id: string | null;
  output_tokens: number | null;
  search_vector: string | null;
  source_type: ContentSourceTypeEnum;
  summary: string | null;
  system_prompt_id: string | null;
  total_duration: number | null;
  user_prompt_id: string | null;
  warning: string | null;
}

export interface GeneratedContentChunks {
  chunk_index: number;
  content: string;
  content_hash: string | null;
  embedding: string | null;
  embedding_model: string | null;
  generated_content_id: string;
  id: string;
}

export interface GeneratedContentDocumentAssociation {
  document_id: string;
  generated_content_id: string;
}

export interface GeneratedContentSourceAssociation {
  created_at: Timestamp | null;
  parent_content_id: string;
  relationship_type: string | null;
  source_content_id: string;
}

export interface GroupPageContent {
  company_group_id: string;
  created_at: Timestamp | null;
  id: string;
  intro_content_id: string | null;
  main_content_id: string | null;
}

export interface GroupPageContentCompany {
  company_id: string;
  group_page_content_id: string;
}

export interface Jobs {
  completed_at: Timestamp | null;
  created_at: Timestamp;
  duration: number | null;
  error: string | null;
  id: string;
  job_type: JobTypeEnum;
  max_retries: number;
  params: Json | null;
  priority: number;
  result: Json | null;
  retry_count: number;
  started_at: Timestamp | null;
  status: JobStatusEnum;
  updated_at: Timestamp;
  worker_id: string | null;
}

export interface ModelConfigs {
  content_hash: string | null;
  created_at: Timestamp;
  id: string;
  model: string;
  options_json: string;
}

export interface PipelineRuns {
  company_id: string;
  completed_at: Timestamp | null;
  error: string | null;
  forms: string[] | null;
  id: string;
  jobs_completed: Generated<number>;
  jobs_created: Generated<number>;
  jobs_failed: Generated<number>;
  metadata: Json | null;
  started_at: Timestamp | null;
  status: PipelineRunStatusEnum;
  trigger: PipelineTriggerEnum;
}

export interface Prompts {
  content: string;
  content_hash: string | null;
  description: string | null;
  id: string;
  name: string;
  role: Promptrole;
}

export interface Ratings {
  comment: string | null;
  content_score: number | null;
  format_score: number | null;
  generated_content_id: string | null;
  id: string;
  tags: string[];
}

export interface DB {
  alembic_version: AlembicVersion;
  companies: Companies;
  company_group_membership: CompanyGroupMembership;
  company_groups: CompanyGroups;
  company_page_content: CompanyPageContent;
  company_page_content_change_report: CompanyPageContentChangeReport;
  company_page_content_filing: CompanyPageContentFiling;
  document_chunks: DocumentChunks;
  document_page_content: DocumentPageContent;
  documents: Documents;
  filing_page_content: FilingPageContent;
  filing_page_content_document: FilingPageContentDocument;
  filings: Filings;
  financial_concepts: FinancialConcepts;
  financial_values: FinancialValues;
  generated_content: GeneratedContent;
  generated_content_chunks: GeneratedContentChunks;
  generated_content_document_association: GeneratedContentDocumentAssociation;
  generated_content_source_association: GeneratedContentSourceAssociation;
  group_page_content: GroupPageContent;
  group_page_content_company: GroupPageContentCompany;
  jobs: Jobs;
  model_configs: ModelConfigs;
  pipeline_runs: PipelineRuns;
  prompts: Prompts;
  ratings: Ratings;
}
